/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intGrafica;

import modelBens.associados;
import modelDAO.associadosDAO;

/**
 *
 * @author jou
 */
public class igcastroAssociados extends javax.swing.JInternalFrame {

    /**
     * Creates new form IGcastroAssociados
     */
    public igcastroAssociados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdVerificar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTel = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNomedoPai = new javax.swing.JTextField();
        txtNomeDaMae = new javax.swing.JTextField();
        txtDatnasc = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        txtQtFIlhos = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        cbVerificar = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro de Associados");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(400, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, -1, -1));

        jLabel2.setText("Data de Nascimento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, -1, -1));

        jLabel3.setText("RG:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, -1, -1));

        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, -1, -1));

        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 223, -1, -1));

        jLabel6.setText("Filhos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, -1, -1));

        jLabel7.setText("Nome do Pai");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 326, -1, -1));

        jLabel8.setText("Nome da Mãe");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 378, -1, -1));

        jLabel17.setText("Trabalha Atualmente?");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 430, -1, -1));

        jLabel18.setText("Telefone:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 473, -1, -1));

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 101, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 23, 306, 30));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 215, 311, -1));
        getContentPane().add(txtNomedoPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 318, 266, -1));
        getContentPane().add(txtNomeDaMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 370, 257, -1));

        try {
            txtDatnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtDatnasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 76, 90, 25));

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 118, 106, -1));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, 101, -1));

        txtQtFIlhos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        txtQtFIlhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtFIlhosActionPerformed(evt);
            }
        });
        getContentPane().add(txtQtFIlhos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 101, -1));

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 80, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 100, -1));

        cbVerificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Nao" }));
        cbVerificar.setToolTipText("");
        getContentPane().add(cbVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 423, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtQtFIlhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtFIlhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtFIlhosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        associados asso = new associados();
        associadosDAO dao = new associadosDAO();
        
        
        asso.setNome((txtNome.getText()));
        //String dia = txtDatnasc.getText().substring(0,2);
        //String mes = txtDatnasc.getText().substring(3,5);
        //String ano = txtDatnasc.getText().substring(6);
        //String dataMysql = ano+mes+dia;
        
        asso.setDataNasc(txtDatnasc.getText());
        asso.setRg(txtRg.getText());
        asso.setCpf(txtCPF.getText());
        asso.setEmail(txtEmail.getText());
        asso.setQtdFIlhos(Integer.parseInt(txtQtFIlhos.getText()));
        asso.setNomeDoPai(txtNomedoPai.getText());
        asso.setNomeDaMae(txtNomeDaMae.getText());
        asso.setEmpregado((String)cbVerificar.getSelectedItem());
        asso.setTelefone(txtTel.getText());
        
        
        
        
        
        dao.creat(asso);
        
        
        txtNome.setText("");
        txtDatnasc.setText(""); 
        txtRg.setText("");
        txtCPF.setText("");
        txtEmail.setText("");
        txtQtFIlhos.setText("");
        txtNomedoPai.setText("");
        txtNomeDaMae.setText("");
        txtTel.setText("");
        txtNome.requestFocus();

    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cbVerificar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.ButtonGroup rdVerificar;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtDatnasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeDaMae;
    private javax.swing.JTextField txtNomedoPai;
    private javax.swing.JFormattedTextField txtQtFIlhos;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
